language: go

go:
  - 1.9
  - master

script: make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - secure: "lYGI9llvslYn8Xsln1ya1qw5ZVSUAiLnLPEALRPj9k8zjzSbXtzKEsZRWbFaGxTUhSPAQOnaU4bBhVuaOL922skHgT1EQ3LDjrCChreUo7phk4Wc5yLwLM2/RAk8XyIZQDtkQrFXktQ5hf5hgnNfI+sr6qkp0LkUbqt7sMaEMybuUaz3Z0iNbEmhRRqKhjLO3X9+i3Q/yATrPyBPaN12pxkfpi0hpD3pYcLa+wjKRDgH98T9UVc25R9VNZib+jAJ07IRjubY8XAwn+71hDWErK6BoXkQ6RuydxruzMaSNCqEeButNofPN8CPERNFHNFzh4vWttCAP82fLJXMMFUDtvUdbwZaPcY+xGpYiMtDkKDH7dMvRK3FW390NQmGyAZdA66ikJByhqMevGZ8vHaEMKNcz9vDQJQRV4cUxRurEj2ySxv1yVgk4ep+W+huc+R2h2QeETMdDk5WWITDEleaS4jpfe+xehOWkRRkF/63WT//v8f9lIxLLIELgi0mmz7tq2tKFz7fpyeUc8XBlsCoJJKLz8Y6y6C8xunashIxI1DrI5WEIJA2/0Iw65TIX8y51iMpwDHnSJrHtP/bklii8lQmVx1xatNj9CZIIyUjFzmBUD4hKHgqVYnjFTD9D3T7FK/iThrg+RJFcmMBEG2yns/zdTm8TIrhb3vsz6bHZ8s=" #DOCKER_EMAIL
    - secure: "flxCxFWtAknoSpAYnG2ds0QgWR5LGC3Lfail+IYDje3PFP9Qg0jVq2FZq0WciLQUvO9F7il5RKDHnKE1rRSdJ92gSYHrh0nqzryJExhBMd1EmTPxdq6y0vt0dDRLRZ1itbRo4vnwPUgx90HwU8tt3bMcqfUWJHiMsyvJKOnKpEBm0bWuNkB/ttW1LFFQQaLerZnac4/EO803PLIctjYpdcrKKudIA1FRiaIdhqPDf8BtB1/ogss4P5kYmewVRQc5UEtIjJ8Loa/hf+KXt42lAuhV2C5HjbhsQ7cKzEskD2as0gq5q5kcQqFxXh3nPbevCTjzYGdu+RU1fTKkjqYYbeB8gDeNY4vcKuXKQ3NnLGeWZFvw1c0nqXIpui92qzv5So054tsq1ikjLl5QaW0GbDQyV9mjBe/ozV/aH9D/DmybaG+oO0gaJaota0CiApNXQx0pEzCPTbzlvmtLaaxC5rj4gZGN779nPf3sVWDbXMwCrnhrkCqsh1EnmaoOV6sHNpfDoj1zvMaEdnagTx79E+NFqNQPSaJMslz2Y/q8R5z+RWCt7QEs3nnn+gJjqzhup3OoW7ynfOnthD6u8wvyoxYPT0GFHrTH+o7F3XJ0Bf8D7JObY+QT5wSx8QMJmJz5CSTOJrDO9hYwCiYLWQPphsd0wZhUd4Rp9YcJSH/yMDo=" #DOCKER_USER
    - secure: "gNAa6Pcb4BLBAL7Q4UZe+E8yn6D+PcI+I+OryxcXvQk8Zf7RPNOkRI5kmFmrAg1ffD46NxXN8qn7yHRoNpyDjOPpM5EIUBNzy8D3C2Dcg8+ZhOTmR4ptTsM+Ct43vn31SYRgEdaPWEJuGXfjuoOKmRAsnEaAzgm43S7i5Fbrp+8JWy08niWFHWrZZSrlPBuseaD1NoyG6h3XkdNtdyIC+tYxBISDtkW8+iPyCVQJ+fkrX9zY6mIOXdCzWoFXj5E2LnyU1Y9lzD79n1TDcy6e13SYqK2VP07MAZyyglF72GmG08Ql9cWS2hB280mfTwzg3DTACRlbhdbf495Pf2UAwcz9QDk/WobwaWhZAs6d8srrf4GroDJkOx3/Lmx4INzNn4D1FP3BFIz1vb58PqfpjxObZosngw/VktRd6pJ9nIDuwgO63PO8e7hvfVtv2hPr9sHQoZ3dsJjhFHrnlt3wkog5XPROwiIo6GQkA0IRwQj4rwFrqnr/Zxxzv6KvFsuqsyrZUL06SrABkiQ6iCywNxtJzt/LaLGx+YoHyO9dUKMJsT7/vcJQ7d7Qu6ZS/5MZ+MW+dbvZAhDdCTbwT47yYPt5sZZGeQS0aZD3K3lyZgGAuHoM6Jr81Q5GhVVDYTjkZ9LzKts18XGLS8DjeUEOVSC/mGIP1B5pxp+9jy2fywY=" #DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  # TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # GATEWAY
  - export GITHUBSTATBOT=githubstatbot
  - docker build -t $GITHUBSTATBOT:$COMMIT .
  - docker tag $GITHUBSTATBOT:$COMMIT $GITHUBSTATBOT:$TAG
  - docker push $GITHUBSTATBOT